version: '3.9'

services:
  db:
    image: postgres:17
    restart: always

    shm_size: 128mb

    ports:
      - '5432:5432'

    environment:
        POSTGRES_USER: ${DB_USER}      # Берётся из .env
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}

  cache:
    image: redis:7.2.4-alpine
    restart: always

    ports:
      - '6379:6379'


